/*
 * ConfigParameters.java
 *
 * Created on September 20, 2004, 12:01 AM
 */

package myserver.ui;


/**
* This code was generated using CloudGarden's Jigloo
* SWT/Swing GUI Builder, which is free for non-commercial
* use. If Jigloo is being used commercially (ie, by a corporation,
* company or business for any purpose whatever) then you
* should purchase a license for each developer using Jigloo.
* Please visit www.cloudgarden.com for details.
* Use of Jigloo implies acceptance of these licensing terms.
* *************************************
* A COMMERCIAL LICENSE HAS NOT BEEN PURCHASED
* for this machine, so Jigloo or this code cannot be used legally
* for any corporate or commercial purpose.
* *************************************
*/
/**
 *
 * @author  Danilo
 */
public class ConfigParameters extends javax.swing.JDialog {
    
    /**
	 * Comment for <code>serialVersionUID</code>
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form ConfigParameters */
    public ConfigParameters(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("null");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(140, 20, 50, 21);

        getContentPane().add(jTextField2);
        jTextField2.setBounds(140, 50, 250, 21);

        jLabel1.setText("TCP/IP Port");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 70, 15);

        jLabel2.setText("Data Base Server");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 50, 100, 15);

        jLabel3.setText("Data Base User");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 80, 100, 15);

        jLabel4.setText("Data Base Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 110, 110, 15);

        getContentPane().add(jTextField3);
        jTextField3.setBounds(140, 80, 250, 21);

        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(140, 110, 250, 23);

        jButton1.setText("Close");
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 160, 61, 25);

        pack();
    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
    
}